---
version: '3'
services:
  database: 
    build: ./db
    ports:
        - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      APP_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/ 

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      NODE_ENV: "production"
      PORT: "8080"
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  client:
    build: ./client
    ports:
      - "8081:8080"
    depends_on:
      - api
    environment:
      VUE_APP_API_URL: http://api:8080/api/v1

volumes:
  database-data: