---

version: '3'
services:
  database:
    build: .
    ports:
        - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      APP_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/ 
volumes:
  database-data: