#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$APP_USER" WITH PASSWORD '$APP_USER_PASSWORD';
    CREATE DATABASE "$APP_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$APP_DB" TO "$APP_USER";
    \\c "$APP_DB";
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL